.\" @(#)$RCSfile: gfalFS.man,v $ $Revision: 1.0 $ $Date: 2012/04/15 13:54:45 $ CERN Adrien Devresse
.\" Copyright (C) 2012-2013 by CERN/IT/GT/DMS
.\" ASL-2.0
.\" All rights reserved
.\"
.TH gfalFS 1 "Date: 2012/04/15 15:00:00 " gfalFS "Filesystem client based on GFAL 2.0"
.SH NAME
\fBgfalFS\fR  - Filesystem client for the GFAL 2.0 toolkit

.SH SYNOPSIS
\fB Mount \fR
.PP		
	    gfalFS [options] mntdir remote_url 
.PP	
\fB Umount \fR
.PP	
	    gfalFS_umount mntdir 
	              
.SH DESCRIPTION
\fBgfalFS\fR is a filesystem allowing to mount any resources supported by the GFAL 2.0 toolkit.
.br
This include any resources accessible by the following protocol : \fB WebDav/HTTP, xrootd, SRM, GridFTP, dCAP, LFC, RFIO... \fR
.br
Please refer to the GFAL 2.0 documentation for the complete list of supported protocols.
.br
The user can seamlessly interacts with grid and cloud storage systems just
as if they are local files.
.PP		
The protocol support depends directly of the GFAL 2.0 plugin configuration.

.SH OPTIONS
.PP
\fB\-d\fR
.RS 5
debug mode - does not act anymore like a daemon and print usefull information about the current operations\&. 
.RE
.PP
.RE
\fB\-g\fR
.RS 5
guid mode - access directly to the file by the guid name on the current lfc\&.
.RE
.PP
\fB\-s\fR
.RS 5
single thread mode - Use only one thread to execute the operations, 
this cause a major slowdown of the execution but guarantee a protection against thread safety problems.
.RE
.PP
\fB\-v\fR
.RS 5
enable verbose mode - print more informations about the current execution, can be use with \fB\-d\fR in case of problems \&. 
.RE	
.PP
\fB\-V\fR
.RS 5
print the version number\&. 
.RE
	   
.SH EXAMPLES
.PP
\fB Mount an WebDav over https directory and execute a directory listing
.BR
.P
        mkdir ~/my_mnt/
.BR
        gfalFS ~/my_mnt davs://lxfsra04a04.cern.ch/dpm/cern.ch/
.BR
        /bin/ls ~/my_mnt
.BR
.P
\fB Mount a local folder in debug mode and execute a directory listing
.P
        mkdir ~/my_mnt/
.BR
        gfalFS ~/my_mnt -v -d file:///etc/
.BR
        /bin/ls ~/my_mnt
.BR
.P

\fB Mount an SRM directory with transparent file operations
.P		
        gfalFS ~/my_mnt srm://cvitbdpm1.cern.ch/dpm/cern.ch/home/dteam/
.BR
        echo "Hello world" > ~/my_mnt/hello
.BR
        cat ~/my_mnt/hello
.BR
        cp ~/my_mnt/hello /tmp/test_hello
.BR
.P
\fB Mount an GRIDFTP directory and create a directory
.P
        gfalFS ~/my_mnt gsiftp://cvitbdpm1.cern.ch/dpm/cern.ch/home/dteam/
.BR
        mkdir ~/my_mnt/testdir
.BR
        stat ~/my_mnt/testdir
.P	
\fB Mount an LFC directory and list the replicas of a file
.P
        gfalFS ~/my_mnt lfc://prod-lfc-shared-central.cern.ch/grid/dteam \fR
        getfattr -n user.replicas ~/my_mnt/test_file \fR
.P
\fB Unmount an existing gfalFS mount point \fR
.P
        gfalFS_umount ~/my_mnt/
.P

.SH SEE ALSO
.BR syslog (3),
.BR gfal2 (3),
.BR

.SH LINKS
.BR https://svnweb.cern.ch/trac/lcgutil/wiki/gfalFS


.SH AUTHORS
Adrien Devresse <adrien.devresse@cern.ch>, Jean-Philippe Baud.
